### ISSUE TITLE
Discuss Mint process

### ISSUE THREAD

**Issue by gabaldon** [otherplane/witty-creatures-3.0#12]

**Comment by guidiaz** [comment]
https://www.notion.so/2022-06-22-e462dd52860d49c9a47abad26a4a71f8

**Comment by guidiaz** [comment]
We'll be having a second discussion on how to implement rarity within the NFT contract

**Comment by guidiaz** [comment]
https://hackmd.io/OtoCOROgShmJpr7T5-fSsA
