### ISSUE TITLE
FTU / general: broken camera on Firefox Mobile

### ISSUE THREAD

**Issue by aesedepece** [otherplane/witty-creatures-3.0#35]
Using the camera API is broken for me on Firefox Mobile. It totally stops JavaScript, which tells me that there's some exception going on.

This is yet to be confirmed, but the issue could be about accessing privacy affecting APIs over plain HTTP. If that's the case, there will be nothing to fix, as we will be serving the game over HTTPS.

**Comment by gabaldon** [comment]
Camera worked well on Firefox once deployed
